### ISSUE TITLE
Scrollbar in search box blocks view

### ISSUE THREAD

**Issue by kabessao** [GeopJr/DNOME#18]
Hi, I've been having problems with long queries in the search bar at the top right of the screen, because the scroll bar shows up as a huge blocky windows-like scroll bar. 
![image](https://github.com/GeopJr/DNOME/assets/22626848/3f5dbb76-f27f-4769-b575-11c775ea670f)

hopefully this theme is still being maintained, because I love this theme.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

The theme is maintenance-only as I no longer use discord. I will not be able to catch bugs like the one you reported (caused by discord changing their stylesheet) for the same reason.

You can get the new release from https://dnome.geopjr.dev/ or by bumping the urls for your preferred injection method!
