### ISSUE TITLE
New Adwaita theme

### ISSUE THREAD

**Issue by LukeVader-IV** [GeopJr/DNOME#4]
with gnome 42 around the corner, a new Adwaita theme will be introduced with LibAdwaita for any GTK 4 applications
you can see the new changes by running either GnomeOS nightly or Fedora 36 beta
otherwise there is this LibAdwaita theme for GTK 3 applications: <a href="https://github.com/lassekongo83/adw-gtk3">lassekongo83/adw-gtk3</a>

**Comment by GeopJr** [comment]
Thanks for raising this issue!

The repo has been pretty abandoned since I stopped dealing with Discord theming, however I can update it to reflect the latest changes. Keep in mind that DNOME only re-colors (and sometimes removes Discord branding), so do not expect it to change the style of components further.

**Comment by GeopJr** [comment]
Hi, you can get the libadwaita version from the `dev` branch - more info: #6
